### ISSUE TITLE
No file selected dialog spawn when canceling search for class files

### ISSUE THREAD

**Issue by ivica3730k** [ntu-sdi/dataset-labelling-tool#19]
![image](https://user-images.githubusercontent.com/17437897/75811401-413ffc00-5d84-11ea-9763-901a9c159cf1.png)

When users cancel loading class file via file dialogue, no file selected error pops up. This could be potentially be done better by creating custom exception like OperationCanceled() which is going to be thrown if the user clicks Cancel button in file dialogue.

Example (for the same functionality in annotation loading)
Code in AnnotationModel

![image](https://user-images.githubusercontent.com/17437897/75811599-a136a280-5d84-11ea-8aad-1d4913d0daa5.png)

And then an exception is caught in AnnotationController

![image](https://user-images.githubusercontent.com/17437897/75811675-c0353480-5d84-11ea-9bbe-a08f48912750.png)

This provides better user experience, as error message will not be spawned in GUI if the user cancels browse operation.

**Comment by PetarPeychev** [comment]
I think this is a very nice suggestion. Makes sense to me.

**Comment by ivica3730k** [comment]
Implemented
